// Writes public/version.js with the deployed commit.
//
// Cloudflare Pages (GitHub-sync deploys) runs this as the build command —
// set Build command: `npm run build` and Build output directory: `public`
// in the Pages project settings. Pages provides CF_PAGES_COMMIT_SHA and
// CF_PAGES_BRANCH at build time; running locally falls back to git.

const fs = require('fs');
const { execSync } = require('child_process');

function shortSha() {
  if (process.env.CF_PAGES_COMMIT_SHA) return process.env.CF_PAGES_COMMIT_SHA.slice(0, 7);
  try {
    return execSync('git rev-parse --short HEAD').toString().trim();
  } catch (e) {
    return null;
  }
}

const sha = shortSha();
const branch = process.env.CF_PAGES_BRANCH || '';
const date = new Date().toISOString().slice(0, 10);
const version = sha
  ? sha + (branch && branch !== 'main' ? ' (' + branch + ')' : '') + ' · ' + date
  : 'dev';

fs.writeFileSync('public/version.js',
  '// Generated by build-version.js — do not edit by hand.\n' +
  'window.APP_VERSION = ' + JSON.stringify(version) + ';\n');

console.log('public/version.js -> ' + version);
